# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0005_auto_20170728_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, help_text='If empty, will be auto-generated', max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Submit', 'Submitter'), ('Review', 'Reviewer')], max_length=6)),
                ('fixed', models.BooleanField(default=False, help_text='Once fixed, this membership cannot be changed')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.GroupConfig')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='If inactive: will skip this trigger.')),
                ('name', models.CharField(help_text='For database display', max_length=100)),
                ('description', models.TextField(default='', help_text='Internal description', max_length=500)),
                ('function', models.CharField(help_text='function from the views.py file', max_length=100)),
                ('args', models.TextField(blank=True, help_text='Comma separated entries')),
                ('kwargs', models.TextField(blank=True, help_text='Comma separated key-value pairs')),
                ('template', models.TextField(blank=True, help_text='This template will be rendered with the variables.')),
                ('lower', models.PositiveSmallIntegerField(help_text='Called if >= to this')),
                ('upper', models.PositiveSmallIntegerField(help_text='Called if <= to this')),
                ('start_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Earliest time for this trigger')),
                ('end_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Latest time for this trigger')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
            ],
        ),
        migrations.AddField(
            model_name='groupconfig',
            name='members',
            field=models.ManyToManyField(through='interactive.Membership', to='basic.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='groupconfig',
            unique_together=set([('group_name', 'entry_point')]),
        ),
    ]
