# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For database display', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('function', models.CharField(help_text='function from the views.py file', max_length=100)),
                ('args', models.TextField(blank=True, help_text='Comma separated entries')),
                ('kwargs', models.TextField(blank=True, help_text='Comma separated key-value pairs')),
                ('lower', models.PositiveSmallIntegerField(help_text='Called if >= to this')),
                ('upper', models.PositiveSmallIntegerField(help_text='Called if <= to this')),
            ],
        ),
    ]
