# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20170727_1854'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint'),
            preserve_default=False,
        ),
    ]
