# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        ('basic', '0005_auto_20170728_1515'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, default=None, help_text='If a group submission, links to group.', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Group')),
                ('grpconf', models.ForeignKey(blank=True, help_text='Not known, until the reviewer visits the page', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.GroupConfig')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
                ('submission', models.ForeignKey(help_text='Not known, until the reviewer visits the page', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
    ]
