# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_trigger_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='active',
            field=models.BooleanField(default=False, help_text='If inactive: will skip this trigger.'),
        ),
    ]
