# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_reviewreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewreport',
            old_name='phase',
            new_name='trigger',
        ),
    ]
