# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_auto_20170728_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='description',
            field=models.TextField(default='', help_text='Internal description', max_length=500),
            preserve_default=False,
        ),
    ]
