# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_trigger_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='template',
            field=models.TextField(blank=True, help_text='This template will be rendered with the variables.'),
        ),
    ]
