# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20170801_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='entry',
            new_name='entry_point',
        ),
        migrations.AlterField(
            model_name='reviewreport',
            name='trigger',
            field=models.ForeignKey(blank=True, help_text='Which trigger is this associated with?', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger'),
        ),
    ]
