# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0006_auto_20170801_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Not known, until the reviewer visits the page', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
