# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0008_remove_trigger_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='submitter_read',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
