# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0009_reviewreport_submitter_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='Used to order reviews'),
        ),
    ]
