# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0010_reviewreport_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewreport',
            old_name='submitter_read',
            new_name='submitter_code',
        ),
    ]
