# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0006_auto_20170811_1245'),
        ('basic', '0005_auto_20170728_1515'),
        ('submissions', '0002_auto_20170802_1047'),
        ('interactive', '0011_auto_20170811_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Used to order reviews')),
                ('unique_code', models.CharField(blank=True, editable=False, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to='basic.Person')),
                ('peer_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewer', to='basic.Person')),
                ('r_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RubricActual')),
                ('submission', models.ForeignKey(blank=True, help_text='Not known, until the reviewer visits the page', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
                ('trigger', models.ForeignKey(blank=True, help_text='Which trigger is this associated with?', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger')),
            ],
        ),
    ]
