# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20170728_1515'),
        ('interactive', '0012_evaluationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchieveConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('achieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.AchieveConfig')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
        ),
        migrations.AddField(
            model_name='achieveconfig',
            name='members',
            field=models.ManyToManyField(through='interactive.Achievement', to='basic.Person'),
        ),
    ]
