# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0014_auto_20170814_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achieveconfig',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description', null=True),
        ),
        migrations.AlterField(
            model_name='achieveconfig',
            name='name',
            field=models.CharField(help_text='Display name', max_length=100),
        ),
    ]
