# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0015_auto_20170814_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='last',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
