# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0018_auto_20170818_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='sort_report',
            field=models.CharField(choices=[('-', '----------'), ('E', 'Evaluation'), ('R', 'Rebuttal')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='peer_reviewer',
            field=models.ForeignKey(blank=True, help_text='The reviewer whose review is appended here. Leave blank for rebuttals.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewer', to='basic.Person'),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Might not be known, until the reviewer visits the page', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
