# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0019_auto_20170821_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreport',
            name='submitter_code',
        ),
    ]
