# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0020_remove_reviewreport_submitter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='sort_report',
            field=models.CharField(choices=[('-', '----------'), ('E', 'Evaluation'), ('R', 'Rebuttal'), ('A', 'Assessment')], default='-', max_length=2),
        ),
    ]
