# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0022_auto_20170828_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achieveconfig',
            old_name='order',
            new_name='score',
        ),
    ]
