# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0023_auto_20170828_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreport',
            name='have_emailed',
        ),
    ]
