# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0024_remove_reviewreport_have_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='prior_code',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
    ]
