# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20170829_1704'),
        ('interactive', '0025_evaluationreport_prior_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='entry_point',
            field=models.ForeignKey(blank=True, help_text='Which entry_point is this associated with?', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint'),
        ),
    ]
