# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0027_auto_20170905_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='deadline_dt',
            field=models.DateTimeField(blank=True, default=None, help_text='Sometimes you want a deadline to use in your logic. Set it here', null=True, verbose_name='Deadline date and time'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='end_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Trigger will not run after the start date/time', null=True, verbose_name='Latest time for this trigger'),
        ),
    ]
