# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0028_auto_20170905_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='deadline_dt',
            field=models.DateTimeField(blank=True, default=None, help_text='Sometimes you want a deadline to use in your logic. Set it here.', null=True, verbose_name='Deadline date and time'),
        ),
    ]
