# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_email_task'),
        ('interactive', '0029_auto_20170905_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieveconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.AchieveConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseConditionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('all_apply', models.BooleanField(default=False, help_text='All rules must pass before it is valid', verbose_name='All rules must apply')),
                ('any_apply', models.BooleanField(default=False, help_text='Any or more rules must pass before it is valid', verbose_name='Any rule applies')),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
            ],
        ),
        migrations.AddField(
            model_name='releasecondition',
            name='rc_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.ReleaseConditionConfig'),
        ),
    ]
