# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0030_auto_20171002_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecondition',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='To order the display for students.'),
        ),
        migrations.AlterField(
            model_name='releasecondition',
            name='rc_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.ReleaseConditionConfig', verbose_name='Release condition set'),
        ),
    ]
