# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0031_auto_20171002_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecondition',
            name='achieveconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.AchieveConfig', verbose_name='Achievement config to be completed'),
        ),
    ]
