# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0032_auto_20171002_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
