# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0034_auto_20171017_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='achieveconfig',
            name='deadline_dt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deadline to reach this achievement'),
        ),
    ]
