# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0036_auto_20180212_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='always_run',
            field=models.BooleanField(default=False, help_text='If selected: will always run, no matter waht the dates and times.'),
        ),
    ]
