# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0037_trigger_always_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupconfig',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger'),
        ),
    ]
