# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_auto_20180209_1050'),
        ('interactive', '0038_groupconfig_trigger'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupconfig',
            unique_together=set([('group_name', 'entry_point', 'trigger')]),
        ),
    ]
