# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0039_auto_20180307_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='display',
            field=models.TextField(blank=True, default='', editable=False, help_text='Auto-generated display information', null=True),
        ),
    ]
