# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-22 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0040_achievement_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
