# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-22 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0041_achievement_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='score',
            new_name='grade',
        ),
    ]
