# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import keyterm.models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterm', '0002_auto_20171103_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytermsetting',
            name='deadline_for_submission',
            field=models.DateTimeField(default=keyterm.models.get_submit_deadline),
        ),
    ]
