# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterm', '0003_keytermsetting_deadline_for_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytermtask',
            name='definition_text',
            field=models.TextField(blank=True, help_text='Capped at 500 characters.', null=True),
        ),
    ]
