# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterm', '0004_auto_20171114_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytermtask',
            name='lookup_hash',
            field=models.CharField(default='None', max_length=16),
        ),
    ]
