# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterm', '0005_keytermtask_lookup_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbs',
            name='vote_type',
            field=models.CharField(choices=[('thumbs-up', 'Thumbs up'), ('Smiley', 'Smiley')], default='thumbs-up', max_length=10),
        ),
    ]
