# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20171115_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='event',
            field=models.CharField(choices=[('login', 'login'), ('start-a-review-session', 'start-a-review-session'), ('continue-review-session', 'continue-review-session'), ('ending-a-review-session', 'ending-a-review-session'), ('reviewing-feedback', 'reviewing-feedback'), ('KT-draft', 'KT-draft'), ('KT-preview', 'KT-preview'), ('KT-submit', 'KT-submit'), ('KT-final', 'KT-final'), ('KT-submit', 'KT-submit'), ('KT-vote', 'KT-vote')], max_length=80),
        ),
    ]
