# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradecategory',
            options={'verbose_name': 'Grade category', 'verbose_name_plural': 'Grade categories'},
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='spread_evenly',
            field=models.BooleanField(default=True, help_text="Spread weight across all items evenly. If 'True': no need to specify weights on the GradeItems. "),
        ),
        migrations.AlterField(
            model_name='learnergrade',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The grade earned by the learner. Between 0.0 and 100.0', max_digits=7, null=True),
        ),
    ]
