# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20170727_1854'),
        ('grades', '0002_auto_20170728_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint'),
        ),
    ]
