# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_gradeitem_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.GradeCategory'),
        ),
    ]
