# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20170811_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeitem',
            old_name='entry',
            new_name='entry_point',
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.GradeCategory'),
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which column order is this item'),
        ),
    ]
