# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0005_auto_20170728_1515'),
        ('interactive', '0006_trigger_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('T', 'Submitted late'), ('F', 'Finished'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet')], default='N', max_length=2)),
                ('is_valid', models.BooleanField(default=False, help_text='Valid if: it was submitted on time, or if this is the most recent submission (there might be older ones).')),
                ('file_upload', models.FileField(upload_to=submissions.models.peerreview_directory_path)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=submissions.models.peerreview_directory_path)),
                ('submitted_file_name', models.CharField(default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datetime_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date and time the learner/group submitted.')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint', verbose_name='Entry point')),
                ('group_submitted', models.ForeignKey(blank=True, default=None, help_text='If a group submission, it links back to it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Group')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
                ('trigger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger', verbose_name='Attached with which Trigger')),
            ],
        ),
    ]
