# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='entry',
            new_name='entry_point',
        ),
    ]
