# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20170821_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('T', 'Submitted late'), ('F', 'Finished'), ('G', 'Being peer-reviewed/graded'), ('N', 'Nothing submitted yet'), ('A', 'Automated (internal)'), ('X', 'File has been deleted from webserver')], default='N', max_length=2),
        ),
    ]
