# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0002_auto_20170802_1047'),
        ('basic', '0005_auto_20170728_1515'),
        ('interactive', '0008_remove_trigger_args'),
    ]

    operations = [
        migrations.CreateModel(
            name='RItemActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RItemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('criterion', models.TextField(help_text='The prompt/criterion for the row in the rubric')),
                ('max_score', models.FloatField(help_text='Highest score achievable here')),
                ('option_type', models.CharField(choices=[('Radio', 'Radio buttons (default)'), ('DropD', 'Dropdown of scores'), ('Chcks', 'Checkbox options: multiple valid answers'), ('LText', 'Long text [HTML Text area]'), ('SText', 'Short text [HTML input=text]')], default='Radio', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ROptionActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('submitted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ritem_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rubric.RItemActual')),
            ],
        ),
        migrations.CreateModel(
            name='ROptionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Usually: 1, 2, 3, 4, etc points')),
                ('criterion', models.TextField(blank=True, help_text='A prompt/criterion to the peers')),
                ('order', models.IntegerField()),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RItemTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RubricActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(verbose_name='When did user start grading?')),
                ('completed', models.DateTimeField(verbose_name='When did user end grading?')),
                ('status', models.CharField(choices=[('A', 'Assigned to grader'), ('P', 'Progressing...'), ('C', 'Completed')], default='A', max_length=2)),
                ('submitted', models.BooleanField(default=False, help_text='Has been completed reviewed AND submitted by peer grader.')),
                ('special_access', models.BooleanField(default=False, help_text='Set to true to allow the "graded_by" person to access it.')),
                ('rubric_code', models.CharField(blank=True, editable=False, max_length=16)),
                ('score', models.FloatField(default=0.0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RubricTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Peer review rubric')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('general_instructions', models.TextField(default='')),
                ('maximum_score', models.FloatField(default=0.0)),
                ('show_order', models.BooleanField(default=True, help_text='Shows the order numbers. e.g "1. Assess ..."; else it just shows: "Assess ..."')),
                ('phase', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Trigger')),
                ('pr_process', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
            ],
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='rubric_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RubricTemplate'),
        ),
        migrations.AddField(
            model_name='rubricactual',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
        migrations.AddField(
            model_name='roptionactual',
            name='roption_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.ROptionTemplate'),
        ),
        migrations.AddField(
            model_name='ritemtemplate',
            name='r_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RubricTemplate'),
        ),
        migrations.AddField(
            model_name='ritemactual',
            name='r_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RubricActual'),
        ),
        migrations.AddField(
            model_name='ritemactual',
            name='ritem_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric.RItemTemplate'),
        ),
    ]
