# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubrictemplate',
            old_name='pr_process',
            new_name='entry_point',
        ),
        migrations.RenameField(
            model_name='rubrictemplate',
            old_name='phase',
            new_name='trigger',
        ),
    ]
