# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0002_auto_20170807_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='submit_button_also_shown_on_top',
            field=models.BooleanField(default=True),
        ),
    ]
