# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0003_rubrictemplate_submit_button_also_shown_on_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='show_maximum_score_per_item',
            field=models.BooleanField(default=True, help_text='Can be over-ridden on a per-item basis also.'),
        ),
    ]
