# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0017_auto_20170816_1526'),
        ('rubric', '0007_rubricactual_eval_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='next_trigger',
            field=models.ForeignKey(blank=True, default=None, help_text='What, if any, is the next trigger associated with this?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_trigger', to='interactive.Trigger'),
        ),
    ]
