# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0008_rubrictemplate_next_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrictemplate',
            name='next_trigger',
            field=models.ForeignKey(blank=True, default=None, help_text='What, if any, is the next trigger associated with this?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_triggers', to='interactive.Trigger'),
        ),
        migrations.AlterField(
            model_name='rubrictemplate',
            name='trigger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='interactive.Trigger'),
        ),
    ]
