# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0009_auto_20170818_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubricactual',
            old_name='eval_code',
            new_name='next_code',
        ),
    ]
