# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0010_auto_20170818_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='show_median_words_with_complaint',
            field=models.BooleanField(default=True, help_text='Shows the word count and complains if below median.'),
        ),
        migrations.AlterField(
            model_name='roptiontemplate',
            name='order',
            field=models.IntegerField(help_text='Start from 1 and work upwards.'),
        ),
    ]
