# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0011_auto_20170818_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='thankyou_template',
            field=models.TextField(default='Thank-you'),
        ),
    ]
