# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0012_rubrictemplate_thankyou_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='hook_function',
            field=models.CharField(default='', help_text='Hook that is called (with r_actual as only input)when the review is completed. Called with async()so it is ok if it is overhead intensive. Hook func must exist in the "interactive" application views.py.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubrictemplate',
            name='thankyou_template',
            field=models.TextField(default='Thank-you ...', help_text='The following replacements are available: {{r_actual}}, {{n_missing}} (number of missing items); {{word_count}}, {{median_words}} of all reviews {{person}} (who just did the review) {{total_score}} and {{percentage}}.'),
        ),
    ]
