# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0014_auto_20170819_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricactual',
            name='evaluated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When did submitter evalute the review?'),
        ),
    ]
