# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0015_rubricactual_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritemtemplate',
            name='num_rows',
            field=models.PositiveSmallIntegerField(default=10, help_text='Height of field, if it is a text box.'),
        ),
    ]
