# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric', '0019_auto_20170825_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrictemplate',
            name='minimum_word_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='If greater than zero, will require the user to fill in a minimum number of words.'),
        ),
    ]
