# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import keyterms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTermSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('max_thumbs', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of thumbs up that can be awarded')),
                ('min_submissions_before_voting', models.PositiveSmallIntegerField(default=10, help_text='Minimum number of submissions before voting can start.')),
                ('deadline_for_voting', models.DateTimeField(default=keyterms.models.get_deadline)),
            ],
            options={
                'verbose_name_plural': 'Key Term Settings',
                'verbose_name': 'Key Term Setting',
            },
        ),
    ]
