# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_auto_20171024_1407'),
        ('keyterms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTermTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyterm', models.CharField(max_length=200)),
                ('image_raw', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_modified', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('definition_text', models.CharField(blank=True, help_text='Capped at 500 characters.', max_length=505, null=True)),
                ('explainer_text', models.TextField(blank=True, null=True)),
                ('reference_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_in_draft', models.BooleanField(default=False, help_text='User is in draft mode')),
                ('is_finalized', models.BooleanField(default=False, help_text='User has submitted, and it is after the deadline')),
                ('is_submitted', models.BooleanField(default=False, help_text='User has submitted')),
                ('allow_to_share', models.BooleanField(default=True, help_text='Student is OK to share their work with class.')),
                ('entry_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.EntryPoint')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyterms.KeyTermSettings')),
            ],
            options={
                'verbose_name_plural': 'Key Term Tasks',
                'verbose_name': 'Key Term Task',
            },
        ),
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded', models.BooleanField(default=False)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('keytermtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyterms.KeyTermTask')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person')),
            ],
            options={
                'verbose_name_plural': 'Thumbs up',
                'verbose_name': 'Thumbs up',
            },
        ),
    ]
