# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterms', '0003_auto_20171025_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytermtask',
            name='is_in_preview',
            field=models.BooleanField(default=False, help_text='Preview mode'),
        ),
    ]
