# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyterms', '0004_keytermtask_is_in_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytermtask',
            name='image_raw',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
