# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyterms', '0005_auto_20171027_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytermtask',
            name='image_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
