# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Course name')),
                ('label', models.CharField(help_text="Obtain this from the HTML POST field: 'context_id' ", max_length=300, verbose_name='LTI POST label context_id')),
                ('base_url', models.CharField(blank=True, help_text='The base URL', max_length=200)),
                ('offering', models.PositiveIntegerField(blank=True, default='0000', help_text='Which year/quarter is it being offered?')),
            ],
        ),
    ]
