# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LTI_system', models.CharField(choices=[('Brightspace-v1', 'Brightspace-v1'), ('edX-v1', 'edX-v1'), ('Coursera-v1', 'Coursera-v1')], max_length=50)),
                ('LTI_id', models.CharField(help_text='In Brightspace LTI post: "resource_link_id"', max_length=50, verbose_name='LTI ID')),
                ('LTI_title', models.CharField(help_text='A title to identify this PR in the database', max_length=300, verbose_name='LTI Title')),
                ('uses_groups', models.BooleanField(default=False, help_text='The workflow and responses are slightly modified if groups are used.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Course')),
            ],
            options={
                'verbose_name': 'Entry point',
                'verbose_name_plural': 'Entry points',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Group name')),
                ('description', models.TextField(blank=True, verbose_name='Detailed group description')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='How many people in this particular group instance?')),
                ('order', models.PositiveIntegerField(default=0, help_text='For ordering purposes in the tables.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Course')),
            ],
        ),
        migrations.CreateModel(
            name='GroupEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='If blank/null: used internally to enrol the rest of the class list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='NOT USED')),
                ('email', models.EmailField(max_length=254)),
                ('student_number', models.CharField(blank=True, default='', max_length=15)),
                ('display_name', models.CharField(blank=True, max_length=400, verbose_name='Display name')),
                ('user_ID', models.CharField(blank=True, max_length=100, verbose_name='User ID from LMS/LTI')),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Learn', 'Learner'), ('TA', 'Teaching Assistant')], default='Learn', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Course')),
            ],
        ),
        migrations.AddField(
            model_name='groupenrolled',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Person'),
        ),
    ]
