# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20170727_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='uses_groups',
            field=models.BooleanField(default=False, help_text='Are groups used to SUBMIT a document?'),
        ),
    ]
