# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20170829_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='full_URL',
            field=models.CharField(default='', help_text='Full URL to the entry point in the given platform.', max_length=255),
        ),
    ]
