# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20170906_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='student_number',
        ),
    ]
