# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_remove_person_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(default='--------------------------------', editable=False, max_length=32)),
                ('was_used', models.BooleanField(default=False)),
                ('time_used', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.AddField(
            model_name='person',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Person'),
        ),
    ]
