# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20170911_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='next_uri',
            field=models.CharField(default='', max_length=254),
        ),
    ]
