# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20170918_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='initials',
            field=models.CharField(blank=True, default='', help_text='Initials of the user (for display)', max_length=5),
        ),
    ]
