# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_person_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Course'),
        ),
    ]
