# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_email_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_lis',
            field=models.CharField(blank=True, max_length=200, verbose_name='Last known: lis_result_sourcedid'),
        ),
    ]
