# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_auto_20171024_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_grade_push_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Last known: lis_outcome_service_url'),
        ),
    ]
