# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_auto_20171114_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='official_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Official name'),
        ),
    ]
