# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_person_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='settings',
            field=models.TextField(blank=True, help_text='Comma separated key-value setting pairs'),
        ),
    ]
