# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_entrypoint_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrypoint',
            name='settings',
        ),
        migrations.AddField(
            model_name='entrypoint',
            name='kwargs',
            field=models.TextField(blank=True, help_text='Dictionary of JSON settings. E.g.: {"num_peers":2}'),
        ),
    ]
