# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_auto_20180209_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kwargs',
            field=models.TextField(blank=True, help_text='JSON settings. E.g. {"num_peers": 2}'),
        ),
    ]
